---
# selfsigned_demo_ca/tasks/generate_demo_ca.yml

- name: 'Demo CA: create the target directory'
  file:
    path: "{{ ca_target_folder }}"
    state: 'directory'
    mode: '0700'

- name: 'Demo CA: Create the private key'
  # module will be renamed from openssl_privatekey to community.crypto.openssl_privatekey
  openssl_privatekey:
    path: "{{ ca_target_folder }}/{{ ca_key_file }}"
    size: "{{ ca_key_size | int }}"
    type: "{{ ca_key_type }}"
    passphrase: "{{ ca_key_passphrase }}"
    cipher: "{{ ca_key_cipher }}"
  register: democa_key_creation

- name: 'Demo CA: create the CSR'
  # module will be renamed from openssl_csr to community.crypto.openssl_csr
  openssl_csr:
    path: "{{ ca_target_folder }}/{{ ca_csr_file }}"
    privatekey_path: "{{ ca_target_folder }}/{{ ca_key_file }}"
    privatekey_passphrase: "{{ ca_key_passphrase }}"
    common_name: "{{ ca_common_name }}"
    organization_name: "{{ ca_organization_name }}"
    country_name: "{{ ca_country_name }}"
    state_or_province_name: "{{ ca_state_or_province_name }}"
    locality_name: "{{ ca_locality_name }}"
    basic_constraints: "{{ ca_basic_constraints }}"
  register: democa_csr_creation

- name: 'Demo CA: sign the CSR'
  # module will be renamed to community.crypto.x509_certificate
  openssl_certificate:
    path: "{{ ca_target_folder }}/{{ ca_crt_file }}"
    csr_path: "{{ ca_target_folder }}/{{ ca_csr_file }}"
    privatekey_path: "{{ ca_target_folder }}/{{ ca_key_file }}"
    privatekey_passphrase: "{{ ca_key_passphrase }}"
    provider: 'selfsigned'
  register: democa_crt_creation
