---
# selfsigned_demo_ca/tasks/main.yml

- name: "Load variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"

#
# pre-flight checks
#
- name: 'fail if variable for rootca is not defined'
  fail:
    msg: 'variable for rootca is not defined'
  when: 'ownca_privatekey_passphrase is undefined'

#
# set variables
#
- name: 'Set variable ca_target_folder if it is undefined'
  set_fact:
    ca_target_folder: "{{ default_ca_target_folder }}"
  when: 'ca_target_folder is undefined'

- name: 'Set variable host_certs_target_folder if it is undefined'
  set_fact:
    host_certs_target_folder: "{{ default_host_certs_target_folder }}"
  when: 'host_certs_target_folder is undefined'

- name: 'Set variable ca_crt_file if it is undefined'
  set_fact:
    ca_crt_file: "{{ default_ca_crt_file }}"
  when: 'ca_crt_file is undefined'

- name: 'Set variable ca_key_file if it is undefined'
  set_fact:
    ca_key_file: "{{ default_ca_key_file }}"
  when: 'ca_key_file is undefined'

#
# install packages
#
- name: 'Install python packages required by ansible'
  import_tasks: install_python_packages.yml
  when: 'create_certs_for_hosts | bool'

#
# setting up a demo CA
#
- name: 'Generate the demo CA'
  import_tasks: generate_demo_ca.yml
  when: 'generate_demo_ca | bool'

#
# creating certificates for the hosts
#
- name: 'create certificates for hosts'
  import_tasks: create_certs_for_hosts.yml
  when: 'create_certs_for_hosts | bool'
