---
# selfsigned_demo_ca/tasks/parse_variables.yml

# code from https://www.samdarwin.com/ansible-default-vars/
- name: 'set facts based on defaults'
  ansible.builtin.set_fact:
    "{{ item[8:] }}": "{{ lookup('vars', item) }}"
  when:
    - item is match("^default_")
    - vars[item[8:]] is not defined
  with_items:
    "{{ vars | list }}"
